# Generated by Django 5.1.6 on 2025-02-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('Nubank', 'Nubank'), ('Santander', 'Santander'), ('Bradesco', 'Bradesco'), ('Itaú', 'Itau'), ('Inter', 'Inter')], default='Nubank', max_length=20)),
                ('valor', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saida')], default='Entrada', max_length=10)),
                ('motivo', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.conta')),
            ],
        ),
    ]
